import React, { useState, useEffect, useMemo, useCallback } from "react";
import { LineChart, Line, AreaChart, Area, BarChart, Bar, RadarChart, Radar, PolarGrid, PolarAngleAxis, ScatterChart, Scatter, XAxis, YAxis, ZAxis, CartesianGrid, Tooltip, ResponsiveContainer, ReferenceLine, Label } from "recharts";
import { parseHealthZip, mergeData } from "./DataParser";
const seed = (i, s = 1) => Math.sin(i * s * 7.3 + s * 13.1) * 0.5 + 0.5;
const generate60Days = () => Array.from({ length: 60 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - (59 - i)); const workoutLoad = i % 3 === 0 ? Math.round(50 + seed(i,2)*60) : i % 5 === 0 ? Math.round(70 + seed(i,3)*40) : Math.round(seed(i,4)*20); const sleepBase = 6.2 + Math.sin(i*0.18)*0.9; const sleep = +(sleepBase + seed(i,1)*1.1).toFixed(1); const lagLoad = i >= 2 ? (i%3===2?80:15) : 20; const hrv = Math.round(38 + Math.sin(i*0.22)*12 + seed(i,5)*8 - lagLoad*0.12 + sleep*1.8); const rhr = Math.round(58-(hrv-38)*0.18+seed(i,6)*5); const readiness = Math.round(Math.min(99,Math.max(30,hrv*0.9+sleep*4-rhr*0.3+seed(i,7)*8))); const steps = Math.round(6000+seed(i,8)*6000+workoutLoad*40); const calories = Math.round(350+workoutLoad*3.2+seed(i,9)*200); const stress = Math.round(Math.max(10,65-readiness*0.5+seed(i,10)*20)); const dt2 = new Date(); dt2.setDate(dt2.getDate()-(59-i)); return { date: d.toISOString().slice(0,10), displayDate: d.toLocaleDateString("en",{month:"short",day:"numeric"}), dayName: d.toLocaleDateString("en",{weekday:"short"}), dayIndex:i, hrv, sleep, rhr, readiness, steps, calories, stress, workoutLoad, deepSleep:+(sleep*(0.15+seed(i,11)*0.1)).toFixed(1), remSleep:+(sleep*(0.18+seed(i,12)*0.08)).toFixed(1), spo2:+(97.2+seed(i,13)*1.6).toFixed(1), activeMinutes:Math.round(20+workoutLoad*0.6+seed(i,14)*30) }; });
const ALL_DATA = generate60Days();
const weekData = ALL_DATA.slice(-7);

const demoWorkouts = [{id:1,name:"Morning Run",type:"run",date:"Today",duration:"42 min",distance:"6.2 km",hr:158,calories:387,load:78},{id:2,name:"Weight Training",type:"strength",date:"Yesterday",duration:"58 min",distance:null,hr:134,calories:312,load:64},{id:3,name:"HIIT Session",type:"hiit",date:"2d ago",duration:"28 min",distance:null,hr:174,calories:298,load:92},{id:4,name:"Evening Walk",type:"walk",date:"3d ago",duration:"35 min",distance:"3.1 km",hr:98,calories:142,load:22},{id:5,name:"Cycling",type:"cycle",date:"4d ago",duration:"68 min",distance:"24.3 km",hr:148,calories:524,load:85}];
const sleepStages=[{stage:"Awake",duration:18,color:"#e74c3c"},{stage:"Light",duration:142,color:"#3498db"},{stage:"Deep",duration:74,color:"#8b5cf6"},{stage:"REM",duration:98,color:"#06b6d4"}];
const pearson=(xs,ys)=>{const n=xs.length;if(n<3)return 0;const mx=xs.reduce((a,b)=>a+b,0)/n;const my=ys.reduce((a,b)=>a+b,0)/n;const num=xs.reduce((s,x,i)=>s+(x-mx)*(ys[i]-my),0);const den=Math.sqrt(xs.reduce((s,x)=>s+(x-mx)**2,0)*ys.reduce((s,y)=>s+(y-my)**2,0));return den===0?0:num/den;};
const lagCorrelation=(data,xKey,yKey,lag)=>{const pairs=data.slice(lag).map((d,i)=>({x:data[i][xKey],y:d[yKey]})).filter(p=>p.x!=null&&p.y!=null);return pearson(pairs.map(p=>p.x),pairs.map(p=>p.y));};
const linearRegression=pts=>{const n=pts.length;if(n<2)return{slope:0,intercept:0};const mx=pts.reduce((s,p)=>s+p.x,0)/n;const my=pts.reduce((s,p)=>s+p.y,0)/n;const slope=pts.reduce((s,p)=>s+(p.x-mx)*(p.y-my),0)/pts.reduce((s,p)=>s+(p.x-mx)**2,1);const intercept=my-slope*mx;return{slope,intercept};};
const METRICS={hrv:{label:"HRV",unit:"ms",color:"#22d3a5"},sleep:{label:"Sleep",unit:"h",color:"#3b82f6"},readiness:{label:"Readiness",unit:"",color:"#8b5cf6"},rhr:{label:"Resting HR",unit:"bpm",color:"#e74c3c"},steps:{label:"Steps",unit:"",color:"#f59e0b"},workoutLoad:{label:"Workout Load",unit:"",color:"#f97316"},stress:{label:"Stress",unit:"",color:"#ec4899"},calories:{label:"Calories",unit:"kcal",color:"#84cc16"},activeMinutes:{label:"Active Min",unit:"min",color:"#06b6d4"}};
const PRESET_PAIRS=[{x:"sleep",y:"hrv",lag:1,label:"Sleep → next-day HRV"},{x:"workoutLoad",y:"hrv",lag:2,label:"Workout → HRV (2d lag)"},{x:"workoutLoad",y:"readiness",lag:1,label:"Workout → next-day Readiness"},{x:"sleep",y:"readiness",lag:1,label:"Sleep → next-day Readiness"},{x:"stress",y:"sleep",lag:1,label:"Stress → next-night Sleep"},{x:"steps",y:"hrv",lag:2,label:"Steps → HRV (2d lag)"}];
const Icon=({name,size=16})=>{const icons={heart:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>,activity:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>,moon:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>,zap:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>,trending:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>,upload:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="16 16 12 12 8 16"/><line x1="12" y1="12" x2="12" y2="21"/><path d="M20.39 18.39A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.3"/></svg>,run:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="13" cy="4" r="2"/><path d="m14.5 10.5-2 4.5-3.5 2-1.5 3"/><path d="m8.5 14.5 2-2 2-1 3-4"/></svg>,droplet:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"/></svg>,close:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>,link:<svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>};return icons[name]||null;};
const ScoreRing=({value,max=100,size=120,strokeWidth=8,color,label,sublabel})=>{const r=(size-strokeWidth*2)/2;const circ=2*Math.PI*r;const dash=circ*(value/max);return(<div style={{position:"relative",width:size,height:size,flexShrink:0}}><svg width={size} height={size} style={{transform:"rotate(-90deg)"}}><circle cx={size/2} cy={size/2} r={r} fill="none" stroke="#1a1d24" strokeWidth={strokeWidth}/><circle cx={size/2} cy={size/2} r={r} fill="none" stroke={color} strokeWidth={strokeWidth} strokeDasharray={`${dash} ${circ}`} strokeLinecap="round" style={{filter:`drop-shadow(0 0 6px ${color}88)`,transition:"stroke-dasharray 1s ease"}}/></svg><div style={{position:"absolute",inset:0,display:"flex",flexDirection:"column",alignItems:"center",justifyContent:"center"}}><span style={{fontSize:size>100?28:20,fontWeight:700,color:"#f0f0f0",fontFamily:"monospace",lineHeight:1}}>{value??"-"}</span>{label&&<span style={{fontSize:10,color:"#888",textTransform:"uppercase",letterSpacing:"0.08em",marginTop:2}}>{label}</span>}{sublabel&&<span style={{fontSize:9,color,marginTop:1}}>{sublabel}</span>}</div></div>);};
const MetricCard=({label,value,unit,icon,color,trend,onClick,active})=>(<div onClick={onClick} style={{background:active?`${color}12`:"#10121a",border:`1px solid ${active?color:"#1e2130"}`,borderRadius:12,padding:"16px 18px",cursor:"pointer",transition:"all 0.2s",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,right:0,width:80,height:80,background:`radial-gradient(circle at top right, ${color}18, transparent 70%)`}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:10}}><span style={{color,opacity:0.85}}><Icon name={icon} size={14}/></span>{trend!==undefined&&<span style={{fontSize:10,color:trend>=0?"#22d3a5":"#e74c3c"}}>{trend>=0?"▲":"▼"} {Math.abs(trend)}%</span>}</div><div style={{fontSize:24,fontWeight:700,color:"#f0f0f0",fontFamily:"monospace",lineHeight:1}}>{value??"-"}<span style={{fontSize:12,color:"#666",fontWeight:400,marginLeft:3}}>{unit}</span></div><div style={{fontSize:11,color:"#666",marginTop:4,textTransform:"uppercase",letterSpacing:"0.06em"}}>{label}</div></div>);
const CustomTooltip=({active,payload,label})=>{if(!active||!payload?.length)return null;return(<div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:8,padding:"10px 14px",fontSize:12}}><div style={{color:"#888",marginBottom:6,textTransform:"uppercase",letterSpacing:"0.06em",fontSize:10}}>{label}</div>{payload.map((p,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",gap:16}}><span style={{color:"#888"}}>{p.name}</span><span style={{color:p.color,fontWeight:700,fontFamily:"monospace"}}>{p.value}</span></div>))}</div>);};
const ScatterTooltip=({active,payload})=>{if(!active||!payload?.length)return null;const d=payload[0]?.payload;if(!d)return null;return(<div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:8,padding:"10px 14px",fontSize:12}}><div style={{color:"#888",fontSize:10,marginBottom:4}}>{d.date}</div>{payload.map((p,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",gap:16}}><span style={{color:"#888"}}>{p.name}</span><span style={{color:p.color||"#f0f0f0",fontWeight:700,fontFamily:"monospace"}}>{p.value}</span></div>))}</div>);};
const corrLabel=r=>{const abs=Math.abs(r);const dir=r>=0?"positive":"negative";if(abs>=0.7)return{text:`Strong ${dir}`,color:r>=0?"#22d3a5":"#e74c3c"};if(abs>=0.4)return{text:`Moderate ${dir}`,color:r>=0?"#f59e0b":"#f97316"};if(abs>=0.2)return{text:`Weak ${dir}`,color:"#888"};return{text:"No clear correlation",color:"#555"};};
const CorrBar=({r,label,xLabel,yLabel,lag,onClick,active})=>{const{text,color}=corrLabel(r);return(<div onClick={onClick} style={{background:active?"#1a1d24":"#10121a",border:`1px solid ${active?"#2a2d3a":"#1e2130"}`,borderRadius:10,padding:"12px 14px",cursor:"pointer",transition:"all 0.15s"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><span style={{fontSize:12,fontWeight:600,color:"#ccc"}}>{label}</span><div style={{display:"flex",alignItems:"center",gap:6}}>{lag>0&&<span style={{fontSize:9,color:"#555",background:"#1a1d24",padding:"2px 6px",borderRadius:4}}>+{lag}d lag</span>}<span style={{fontSize:13,fontWeight:700,fontFamily:"monospace",color}}>{r>=0?"+":""}{r.toFixed(2)}</span></div></div><div style={{height:4,background:"#1a1d24",borderRadius:2,overflow:"hidden",marginBottom:6}}><div style={{height:"100%",width:`${Math.abs(r)*100}%`,background:color,borderRadius:2,transition:"width 0.6s ease",boxShadow:`0 0 8px ${color}66`}}/></div><div style={{fontSize:10,color}}>{text} · <span style={{color:"#555"}}>{xLabel} → {yLabel}</span></div></div>);};
const LagRow=({xKey,yKey,data})=>{const lags=[0,1,2,3,4];const corrs=lags.map(lag=>lagCorrelation(data,xKey,yKey,lag));const mx=METRICS[xKey];const my=METRICS[yKey];return(<div style={{display:"flex",alignItems:"center",gap:8,padding:"8px 0",borderBottom:"1px solid #1a1d24"}}><div style={{width:160,fontSize:11,color:"#888",flexShrink:0}}><span style={{color:mx.color}}>{mx.label}</span> → <span style={{color:my.color}}>{my.label}</span></div>{corrs.map((r,i)=>{const abs=Math.abs(r);const bg=r>0?`rgba(34,211,165,${abs*0.85})`:`rgba(231,76,60,${abs*0.85})`;return(<div key={i} style={{flex:1,height:32,background:bg,borderRadius:5,display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,fontWeight:700,fontFamily:"monospace",color:abs>0.3?"#000":"#555",border:"1px solid #1a1d24"}}>{r.toFixed(2)}</div>);})}</div>);};
const SleepBreakdown=({data})=>{const total=data.reduce((s,d)=>s+d.duration,0);return(<div><div style={{display:"flex",height:10,borderRadius:5,overflow:"hidden",marginBottom:16,gap:2}}>{data.map((s,i)=><div key={i} style={{flex:s.duration,background:s.color,borderRadius:3,boxShadow:`0 0 8px ${s.color}66`}}/>)}</div><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>{data.map((s,i)=>(<div key={i} style={{display:"flex",alignItems:"center",gap:8}}><div style={{width:8,height:8,borderRadius:2,background:s.color,flexShrink:0,boxShadow:`0 0 6px ${s.color}88`}}/><div><div style={{fontSize:11,color:"#f0f0f0",fontWeight:600}}>{Math.floor(s.duration/60)}h {s.duration%60}m</div><div style={{fontSize:10,color:"#555"}}>{s.stage} · {Math.round(s.duration/total*100)}%</div></div></div>))}</div></div>);};
const typeColors={run:"#22d3a5",strength:"#8b5cf6",hiit:"#e74c3c",walk:"#3b82f6",cycle:"#f59e0b",default:"#888"};
const WorkoutCard=({w})=>(<div style={{display:"flex",alignItems:"center",gap:14,padding:"14px 0",borderBottom:"1px solid #1a1d24"}}><div style={{width:40,height:40,borderRadius:10,background:`${typeColors[w.type]||typeColors.default}18`,border:`1px solid ${typeColors[w.type]||typeColors.default}44`,display:"flex",alignItems:"center",justifyContent:"center",color:typeColors[w.type]||typeColors.default,flexShrink:0}}><Icon name="run" size={16}/></div><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,color:"#f0f0f0"}}>{w.name}</div><div style={{fontSize:11,color:"#555",marginTop:2}}>{w.date||w.startTime?.slice(0,10)} · {w.duration} min{w.distance?` · ${w.distance}km`:""}</div></div><div style={{textAlign:"right"}}>{w.hr&&<div style={{fontSize:12,color:"#888"}}><span style={{color:"#e74c3c",fontFamily:"monospace",fontWeight:700}}>{w.hr}</span> bpm</div>}<div style={{fontSize:11,color:"#555",marginTop:2}}>{w.calories?`${w.calories} kcal`:""}</div></div></div>);
const Select=({value,onChange,options,color="#22d3a5"})=>(<select value={value} onChange={e=>onChange(e.target.value)} style={{background:"#1a1d24",border:`1px solid ${color}44`,borderRadius:8,color,padding:"6px 10px",fontSize:12,fontWeight:600,cursor:"pointer",outline:"none",fontFamily:"inherit"}}>{options.map(o=><option key={o.value} value={o.value} style={{background:"#10121a"}}>{o.label}</option>)}</select>);

const UploadModal=({onClose,onDataLoaded})=>{
  const [dragging,setDragging]=useState(false);
  const [queued,setQueued]=useState([]);
  const [parsing,setParsing]=useState(false);
  const fileRef=React.useRef();
  const addFiles=files=>{setQueued(prev=>[...prev,...Array.from(files).map(f=>({file:f,name:f.name,size:(f.size/1024).toFixed(0)+" KB",status:"ready",source:null,error:null}))]);};
  const handleDrop=e=>{e.preventDefault();setDragging(false);addFiles(e.dataTransfer.files);};
  const handleProcess=async()=>{
    setParsing(true);
    const results={ultrahuman:null,zepp:null};
    const updated=[...queued];
    for(let i=0;i<updated.length;i++){
      const q=updated[i];if(q.status!=="ready")continue;
      try{
        updated[i]={...q,status:"parsing"};setQueued([...updated]);
        const{source,data}=await parseHealthZip(q.file);
        results[source]=data;
        updated[i]={...q,status:"done",source};setQueued([...updated]);
      }catch(err){updated[i]={...q,status:"error",error:err.message};setQueued([...updated]);}
    }
    const uh=results.ultrahuman||[];const zp=results.zepp||[];
    let merged;
    if(uh.length&&zp.length)merged=mergeData(uh,zp);
    else if(uh.length)merged=mergeData(uh,[]);
    else if(zp.length)merged=mergeData([],zp);
    if(merged?.length){onDataLoaded(merged);setTimeout(onClose,800);}
    setParsing(false);
  };
  const sc={ready:"#666",parsing:"#f59e0b",done:"#22d3a5",error:"#e74c3c"};
  const sl={ready:"Ready",parsing:"Parsing…",done:"Loaded ✓",error:"Error"};
  return(<div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.88)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",backdropFilter:"blur(6px)"}}><div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:16,padding:32,width:520,maxWidth:"94vw"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h2 style={{color:"#f0f0f0",fontSize:18,fontWeight:700,margin:0}}>Import Health Data</h2><button onClick={onClose} style={{background:"none",border:"none",color:"#666",cursor:"pointer"}}><Icon name="close" size={18}/></button></div><div style={{display:"flex",gap:8,marginBottom:16}}>{[{key:"ultrahuman",hint:"Ultrahuman app → Profile → Export Data → ZIP"},{key:"zepp",hint:"Zepp app → Profile → My Data → Export → ZIP"}].map(s=>(<div key={s.key} style={{flex:1,background:"#1a1d24",borderRadius:10,padding:"10px 12px"}}><div style={{fontSize:11,fontWeight:700,color:"#22d3a5",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:4}}>{s.key}</div><div style={{fontSize:10,color:"#555",lineHeight:1.5}}>{s.hint}</div></div>))}</div><div onClick={()=>fileRef.current?.click()} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={handleDrop} style={{border:`2px dashed ${dragging?"#22d3a5":"#1e2130"}`,borderRadius:12,padding:"28px 20px",textAlign:"center",background:dragging?"#22d3a510":"#0d0f18",transition:"all 0.2s",cursor:"pointer"}}><div style={{color:dragging?"#22d3a5":"#444",marginBottom:8}}><Icon name="upload" size={26}/></div><div style={{color:"#888",fontSize:13}}>Drop your Ultrahuman or Zepp ZIP here</div><div style={{color:"#555",fontSize:11,marginTop:3}}>or tap to browse — you can add both at once</div></div><input ref={fileRef} type="file" accept=".zip" multiple onChange={e=>addFiles(e.target.files)} style={{display:"none"}}/>{queued.length>0&&(<div style={{marginTop:14,display:"flex",flexDirection:"column",gap:6}}>{queued.map((f,i)=>(<div key={i} style={{display:"flex",justifyContent:"space-between",alignItems:"center",background:"#1a1d24",borderRadius:8,padding:"8px 12px"}}><div><span style={{fontSize:12,color:"#ccc"}}>{f.name}</span>{f.source&&<span style={{fontSize:10,color:"#22d3a5",marginLeft:8}}>{f.source}</span>}{f.error&&<div style={{fontSize:10,color:"#e74c3c",marginTop:2}}>{f.error}</div>}</div><span style={{fontSize:11,color:sc[f.status],fontWeight:600}}>{f.size} · {sl[f.status]}</span></div>))}<button onClick={handleProcess} disabled={parsing||queued.every(f=>f.status==="done")} style={{marginTop:6,background:parsing?"#1a1d24":"#22d3a5",color:parsing?"#666":"#000",border:"none",borderRadius:8,padding:"11px 0",fontWeight:700,fontSize:13,cursor:parsing?"not-allowed":"pointer",transition:"all 0.2s"}}>{parsing?"PARSING YOUR DATA…":"PROCESS & LOAD INTO DASHBOARD"}</button></div>)}</div></div>);};

const CorrelationsTab=({data})=>{
  const[xKey,setXKey]=useState("sleep");const[yKey,setYKey]=useState("hrv");const[lag,setLag]=useState(1);const[activePreset,setActivePreset]=useState(0);
  const metricOptions=Object.entries(METRICS).map(([k,v])=>({value:k,label:v.label}));
  const applyPreset=i=>{const p=PRESET_PAIRS[i];setXKey(p.x);setYKey(p.y);setLag(p.lag);setActivePreset(i);};
  const scatterData=useMemo(()=>data.slice(lag).map((d,i)=>({x:data[i][xKey],y:d[yKey],date:d.date||d.displayDate})).filter(p=>p.x!=null&&p.y!=null),[data,xKey,yKey,lag]);
  const regLine=useMemo(()=>{if(scatterData.length<3)return[];const{slope,intercept}=linearRegression(scatterData);const xs=scatterData.map(p=>p.x);const mn=Math.min(...xs);const mx2=Math.max(...xs);return[{x:mn,y:+(slope*mn+intercept).toFixed(2)},{x:mx2,y:+(slope*mx2+intercept).toFixed(2)}];},[scatterData]);
  const r=useMemo(()=>pearson(scatterData.map(p=>p.x),scatterData.map(p=>p.y)),[scatterData]);
  const{text:rText,color:rColor}=corrLabel(r);
  const mx=METRICS[xKey];const my=METRICS[yKey];
  const presetCorrs=useMemo(()=>PRESET_PAIRS.map(p=>({...p,r:lagCorrelation(data,p.x,p.y,p.lag)})),[data]);
  const lagSweep=useMemo(()=>Array.from({length:8},(_,i)=>({lag:i,r:+lagCorrelation(data,xKey,yKey,i).toFixed(3)})),[data,xKey,yKey]);
  const heatmapPairs=[["workoutLoad","hrv"],["workoutLoad","readiness"],["workoutLoad","sleep"],["sleep","hrv"],["sleep","readiness"],["stress","hrv"],["steps","readiness"],["rhr","readiness"]];
  return(<div style={{display:"flex",flexDirection:"column",gap:20}}>
    <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:12}}>{presetCorrs.slice(0,3).map((p,i)=>{const{color}=corrLabel(p.r);return(<div key={i} onClick={()=>applyPreset(i)} style={{background:activePreset===i?"#1a1d24":"#10121a",border:`1px solid ${activePreset===i?color:"#1e2130"}`,borderRadius:12,padding:"14px 16px",cursor:"pointer",transition:"all 0.15s"}}><div style={{fontSize:10,color:"#555",textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:6}}>{p.label}</div><div style={{fontSize:28,fontWeight:800,fontFamily:"monospace",color}}>{p.r>=0?"+":""}{p.r.toFixed(2)}</div><div style={{fontSize:10,color,marginTop:4}}>{corrLabel(p.r).text}</div></div>);})}</div>
    <div style={{display:"grid",gridTemplateColumns:"300px 1fr",gap:16}}>
      <div style={{display:"flex",flexDirection:"column",gap:12}}>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:18}}>
          <div style={{fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.08em",color:"#888",marginBottom:14}}>Configure</div>
          <div style={{display:"flex",flexDirection:"column",gap:12}}>
            <div><div style={{fontSize:10,color:"#555",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>X axis (cause)</div><Select value={xKey} onChange={v=>{setXKey(v);setActivePreset(-1);}} options={metricOptions} color={mx.color}/></div>
            <div><div style={{fontSize:10,color:"#555",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>Y axis (effect)</div><Select value={yKey} onChange={v=>{setYKey(v);setActivePreset(-1);}} options={metricOptions} color={my.color}/></div>
            <div><div style={{fontSize:10,color:"#555",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>Lag (days after X)</div><div style={{display:"flex",gap:4}}>{[0,1,2,3,4].map(l=>(<button key={l} onClick={()=>{setLag(l);setActivePreset(-1);}} style={{flex:1,padding:"6px 0",borderRadius:6,fontSize:12,fontWeight:700,background:lag===l?"#22d3a5":"#1a1d24",border:`1px solid ${lag===l?"#22d3a5":"#2a2d3a"}`,color:lag===l?"#000":"#666",cursor:"pointer",transition:"all 0.15s"}}>{l}d</button>))}</div></div>
          </div>
          <div style={{marginTop:16,paddingTop:14,borderTop:"1px solid #1a1d24"}}><div style={{fontSize:28,fontWeight:800,fontFamily:"monospace",color:rColor}}>{r>=0?"+":""}{r.toFixed(2)}</div><div style={{fontSize:11,color:rColor,marginTop:2}}>{rText}</div><div style={{fontSize:10,color:"#555",marginTop:8,lineHeight:1.5}}>{Math.abs(r)>=0.4?`When ${mx.label} is higher, ${my.label} tends to be ${r>0?"higher":"lower"} ${lag>0?`${lag} day${lag>1?"s":""} later`:"on the same day"}.`:`No strong relationship found between ${mx.label} and ${my.label} at ${lag}d lag.`}</div></div>
        </div>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:18}}><div style={{fontSize:11,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.08em",color:"#888",marginBottom:12}}>Preset Insights</div><div style={{display:"flex",flexDirection:"column",gap:8}}>{presetCorrs.map((p,i)=>(<CorrBar key={i} r={p.r} label={p.label} xLabel={METRICS[p.x].label} yLabel={METRICS[p.y].label} lag={p.lag} onClick={()=>applyPreset(i)} active={activePreset===i}/>))}</div></div>
      </div>
      <div style={{display:"flex",flexDirection:"column",gap:16}}>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:16}}><div><div style={{fontSize:13,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.04em"}}><span style={{color:mx.color}}>{mx.label}</span><span style={{color:"#444",margin:"0 8px"}}>→{lag>0?` +${lag}d →`:""}</span><span style={{color:my.color}}>{my.label}</span></div><div style={{fontSize:11,color:"#555",marginTop:4}}>{scatterData.length} data points</div></div><div style={{fontSize:22,fontWeight:800,fontFamily:"monospace",color:rColor}}>{r>=0?"+":""}{r.toFixed(2)}</div></div>
          <ResponsiveContainer width="100%" height={240}><ScatterChart margin={{top:10,right:10,bottom:20,left:10}}><CartesianGrid strokeDasharray="3 3" stroke="#1a1d24"/><XAxis dataKey="x" type="number" name={mx.label} tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false} domain={["auto","auto"]}><Label value={mx.label} offset={-10} position="insideBottom" style={{fill:mx.color,fontSize:10,textTransform:"uppercase"}}/></XAxis><YAxis dataKey="y" type="number" name={my.label} tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false} width={38} domain={["auto","auto"]}><Label value={my.label} angle={-90} position="insideLeft" style={{fill:my.color,fontSize:10,textTransform:"uppercase"}}/></YAxis><ZAxis range={[35,35]}/><Tooltip content={<ScatterTooltip/>}/><Scatter data={scatterData} fill={mx.color} fillOpacity={0.6}/><Scatter data={regLine} fill="none" line={{stroke:rColor,strokeWidth:2,strokeDasharray:"5 3"}} shape={()=>null} legendType="none"/></ScatterChart></ResponsiveContainer>
        </div>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:6}}>Lag Sweep</div><div style={{fontSize:11,color:"#555",marginBottom:12}}>How correlation shifts as you move {my.label} forward in time</div><ResponsiveContainer width="100%" height={150}><BarChart data={lagSweep} margin={{top:5,right:5,bottom:0,left:0}}><CartesianGrid strokeDasharray="3 3" stroke="#1a1d24" vertical={false}/><XAxis dataKey="lag" tickFormatter={v=>`+${v}d`} tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false}/><YAxis domain={[-1,1]} tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false} width={35}/><Tooltip content={<CustomTooltip/>}/><ReferenceLine y={0} stroke="#2a2d3a"/><Bar dataKey="r" name="r" radius={[3,3,0,0]} fill="#22d3a5"/></BarChart></ResponsiveContainer><div style={{fontSize:10,color:"#555",marginTop:8}}>Peak at lag +{lagSweep.reduce((a,b)=>Math.abs(b.r)>Math.abs(a.r)?b:a).lag}d (r={lagSweep.reduce((a,b)=>Math.abs(b.r)>Math.abs(a.r)?b:a).r})</div></div>
      </div>
    </div>
    <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:4}}>Lag Correlation Heatmap</div><div style={{fontSize:11,color:"#555",marginBottom:14}}>All metric pairs · 0–4 day lags · Green = positive · Red = negative</div><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><div style={{width:160}}/>{[0,1,2,3,4].map(l=>(<div key={l} style={{flex:1,textAlign:"center",fontSize:10,color:"#555",textTransform:"uppercase"}}>+{l}d</div>))}</div>{heatmapPairs.map(([x,y],i)=><LagRow key={i} xKey={x} yKey={y} data={data}/>)}</div>
  </div>);};

export default function App(){
  const[tab,setTab]=useState("overview");
  const[range,setRange]=useState("7d");
  const[showUpload,setShowUpload]=useState(false);
  const[activeMetric,setActiveMetric]=useState("hrv");
  const[animIn,setAnimIn]=useState(false);
  const[realData,setRealData]=useState(null);
  useEffect(()=>{setTimeout(()=>setAnimIn(true),100);},[]);
  const handleDataLoaded=useCallback(merged=>{setRealData(merged);setRange("30d");},[]);
  const ALL_ACTIVE=realData||ALL_DATA;
  const sliceN=range==="7d"?7:range==="14d"?14:range==="30d"?30:60;
  const data=ALL_ACTIVE.slice(-sliceN).map(d=>({...d,day:d.dayName||d.date}));
  const todayRaw=ALL_ACTIVE[ALL_ACTIVE.length-1];
  const demo=weekData[weekData.length-1];
  const today={hrv:todayRaw.hrv??demo.hrv,sleep:todayRaw.sleep??demo.sleep,rhr:todayRaw.rhr??demo.rhr,spo2:todayRaw.spo2??demo.spo2,steps:todayRaw.steps??demo.steps,activeMinutes:todayRaw.activeMinutes??demo.activeMinutes,calories:todayRaw.calories??demo.calories,workoutLoad:todayRaw.workoutLoad??demo.workoutLoad,readiness:todayRaw.readiness??demo.readiness};
  const tabs=[{id:"overview",label:"Overview",icon:"zap"},{id:"recovery",label:"Recovery",icon:"heart"},{id:"sleep",label:"Sleep",icon:"moon"},{id:"activity",label:"Activity",icon:"activity"},{id:"correlations",label:"Correlations",icon:"link"},{id:"trends",label:"Trends",icon:"trending"}];
  const metricColors={hrv:"#22d3a5",readiness:"#8b5cf6",sleep:"#3b82f6",rhr:"#e74c3c",steps:"#f59e0b",spo2:"#06b6d4"};
  const allWorkouts=realData?realData.flatMap(d=>d.workouts||[]).slice(-10):demoWorkouts;

  return(<div style={{minHeight:"100vh",background:"#080a10",fontFamily:"'Syne','DM Sans',system-ui,sans-serif",color:"#f0f0f0",opacity:animIn?1:0,transform:animIn?"none":"translateY(8px)",transition:"opacity 0.5s ease,transform 0.5s ease"}}>
    <style>{`@import url('https://fonts.googleapis.com/css2?family=Syne:wght@400;600;700;800&family=DM+Mono:wght@400;500&family=DM+Sans:wght@400;500;600&display=swap');*{box-sizing:border-box;margin:0;padding:0;}::-webkit-scrollbar{width:4px;}::-webkit-scrollbar-track{background:#080a10;}::-webkit-scrollbar-thumb{background:#1e2130;border-radius:2px;}button,select{font-family:inherit;}select option{background:#10121a;}`}</style>
    {showUpload&&<UploadModal onClose={()=>setShowUpload(false)} onDataLoaded={handleDataLoaded}/>}
    <div style={{padding:"20px 24px 16px",display:"flex",justifyContent:"space-between",alignItems:"center",borderBottom:"1px solid #1a1d24"}}>
      <div style={{display:"flex",alignItems:"baseline",gap:10}}><span style={{fontSize:20,fontWeight:800,letterSpacing:"-0.02em"}}>VITAL<span style={{color:"#22d3a5"}}>OS</span></span><span style={{fontSize:10,color:"#444",letterSpacing:"0.12em",textTransform:"uppercase"}}>Health Intelligence</span></div>
      <div style={{display:"flex",gap:8,alignItems:"center"}}>
        <div style={{display:"flex",gap:4,background:"#10121a",border:"1px solid #1e2130",borderRadius:8,padding:3}}>{["7d","14d","30d","60d"].map(r=>(<button key={r} onClick={()=>setRange(r)} style={{padding:"4px 10px",borderRadius:6,fontSize:11,fontWeight:600,background:range===r?"#22d3a5":"transparent",color:range===r?"#000":"#555",border:"none",cursor:"pointer",transition:"all 0.15s"}}>{r.toUpperCase()}</button>))}</div>
        <button onClick={()=>setShowUpload(true)} style={{display:"flex",alignItems:"center",gap:6,padding:"7px 14px",background:"#10121a",border:"1px solid #1e2130",borderRadius:8,color:"#22d3a5",fontSize:12,fontWeight:600,cursor:"pointer"}}><Icon name="upload" size={13}/> IMPORT</button>
      </div>
    </div>
    <div style={{display:"flex",padding:"0 24px",borderBottom:"1px solid #1a1d24",overflowX:"auto"}}>{tabs.map(t=>(<button key={t.id} onClick={()=>setTab(t.id)} style={{display:"flex",alignItems:"center",gap:6,padding:"14px 18px",background:"none",border:"none",cursor:"pointer",fontSize:12,fontWeight:600,color:tab===t.id?"#f0f0f0":"#444",letterSpacing:"0.06em",textTransform:"uppercase",borderBottom:tab===t.id?"2px solid #22d3a5":"2px solid transparent",transition:"all 0.15s",whiteSpace:"nowrap"}}><span style={{color:tab===t.id?"#22d3a5":"#333"}}><Icon name={t.icon} size={13}/></span>{t.label}{t.id==="correlations"&&<span style={{fontSize:8,background:"#22d3a522",color:"#22d3a5",padding:"1px 5px",borderRadius:3,fontWeight:700}}>NEW</span>}</button>))}</div>
    <div style={{padding:"20px 24px 40px",maxWidth:1280}}>
      {realData&&(<div style={{marginBottom:16,background:"#22d3a512",border:"1px solid #22d3a533",borderRadius:10,padding:"10px 16px",display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:12,color:"#22d3a5"}}>✓ Real data loaded — {realData.length} days · {realData.filter(d=>d.source==="both").length} days merged from both devices</span><button onClick={()=>setRealData(null)} style={{fontSize:11,color:"#555",background:"none",border:"none",cursor:"pointer"}}>Use demo</button></div>)}

      {tab==="correlations"&&<CorrelationsTab data={ALL_ACTIVE}/>}

      {tab==="overview"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
        <div style={{display:"grid",gridTemplateColumns:"280px 1fr",gap:16}}>
          <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:24}}>
            <div style={{fontSize:10,color:"#555",textTransform:"uppercase",letterSpacing:"0.1em",marginBottom:16}}>Today's Readiness</div>
            <div style={{display:"flex",flexDirection:"column",alignItems:"center",gap:16}}>
              <ScoreRing value={today.readiness} size={140} strokeWidth={10} color="#22d3a5" label="Readiness" sublabel={today.readiness>=70?"Optimal":today.readiness>=50?"Good":"Rest"}/>
              <div style={{width:"100%",display:"flex",flexDirection:"column",gap:8}}>{[{label:"HRV",value:today.hrv,max:80,color:"#22d3a5",unit:"ms"},{label:"RHR",value:today.rhr,max:70,color:"#e74c3c",unit:"bpm"},{label:"SpO₂",value:today.spo2,max:100,color:"#06b6d4",unit:"%"}].map(m=>(<div key={m.label}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><span style={{fontSize:10,color:"#555",textTransform:"uppercase",letterSpacing:"0.06em"}}>{m.label}</span><span style={{fontSize:12,color:"#f0f0f0",fontFamily:"monospace",fontWeight:600}}>{m.value??"-"}{m.unit}</span></div><div style={{height:3,background:"#1a1d24",borderRadius:2,overflow:"hidden"}}><div style={{height:"100%",width:`${((m.value||0)/m.max)*100}%`,background:m.color,borderRadius:2,boxShadow:`0 0 8px ${m.color}88`,transition:"width 1s ease"}}/></div></div>))}</div>
            </div>
          </div>
          <div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,alignContent:"start"}}>
            <MetricCard label="HRV" value={today.hrv} unit="ms" icon="heart" color="#22d3a5" active={activeMetric==="hrv"} onClick={()=>setActiveMetric("hrv")}/>
            <MetricCard label="Sleep" value={today.sleep} unit="h" icon="moon" color="#3b82f6" active={activeMetric==="sleep"} onClick={()=>setActiveMetric("sleep")}/>
            <MetricCard label="Resting HR" value={today.rhr} unit="bpm" icon="heart" color="#e74c3c" active={activeMetric==="rhr"} onClick={()=>setActiveMetric("rhr")}/>
            <MetricCard label="Steps" value={today.steps?.toLocaleString()} unit="" icon="activity" color="#f59e0b" active={activeMetric==="steps"} onClick={()=>setActiveMetric("steps")}/>
            <MetricCard label="Active Min" value={today.activeMinutes} unit="min" icon="zap" color="#8b5cf6" active={activeMetric==="activeMinutes"} onClick={()=>setActiveMetric("activeMinutes")}/>
            <MetricCard label="SpO₂" value={today.spo2} unit="%" icon="droplet" color="#06b6d4" active={activeMetric==="spo2"} onClick={()=>setActiveMetric("spo2")}/>
          </div>
        </div>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}>
          <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}>
            <div><div style={{fontSize:13,fontWeight:700,letterSpacing:"0.04em",textTransform:"uppercase"}}>{activeMetric.toUpperCase()} Trend</div><div style={{fontSize:11,color:"#555",marginTop:2}}>Click a metric card to explore</div></div>
            <div style={{display:"flex",gap:4,flexWrap:"wrap"}}>{Object.entries(metricColors).map(([k,c])=>(<button key={k} onClick={()=>setActiveMetric(k)} style={{padding:"4px 10px",borderRadius:6,fontSize:10,fontWeight:600,background:activeMetric===k?c:"transparent",color:activeMetric===k?"#000":c,border:`1px solid ${c}44`,cursor:"pointer",letterSpacing:"0.06em",textTransform:"uppercase",transition:"all 0.15s"}}>{k}</button>))}</div>
          </div>
          <ResponsiveContainer width="100%" height={200}><AreaChart data={data} margin={{top:5,right:5,bottom:0,left:0}}><defs><linearGradient id="mg" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={metricColors[activeMetric]||"#22d3a5"} stopOpacity={0.3}/><stop offset="95%" stopColor={metricColors[activeMetric]||"#22d3a5"} stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#1a1d24" vertical={false}/><XAxis dataKey="day" tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false} width={35}/><Tooltip content={<CustomTooltip/>}/><Area type="monotone" dataKey={activeMetric} name={activeMetric.toUpperCase()} stroke={metricColors[activeMetric]||"#22d3a5"} fill="url(#mg)" strokeWidth={2} dot={false} activeDot={{r:4}}/></AreaChart></ResponsiveContainer>
        </div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:16}}>Last Night's Sleep</div><div style={{display:"flex",gap:12,alignItems:"center",marginBottom:16}}><ScoreRing value={Math.round((today.sleep||0)*10)} max={100} size={80} strokeWidth={7} color="#3b82f6"/><div><div style={{fontSize:28,fontWeight:700,fontFamily:"monospace",color:"#f0f0f0"}}>{today.sleep??"-"}h</div><div style={{fontSize:11,color:"#555"}}>Total sleep</div></div></div><SleepBreakdown data={sleepStages}/></div>
          <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:4}}>Recent Workouts</div>{allWorkouts.slice(0,4).map((w,i)=><WorkoutCard key={i} w={w}/>)}</div>
        </div>
      </div>)}

      {tab==="recovery"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr 1fr",gap:14}}>{[{label:"HRV Score",value:today.hrv,color:"#22d3a5",desc:"Higher = better recovered"},{label:"Resting HR",value:today.rhr,color:"#e74c3c",desc:"Lower = better recovered"},{label:"Readiness",value:today.readiness,color:"#8b5cf6",desc:"Combined recovery score"}].map(m=>(<div key={m.label} style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20,textAlign:"center"}}><div style={{fontSize:10,color:"#555",textTransform:"uppercase",letterSpacing:"0.1em",marginBottom:14}}>{m.label}</div><ScoreRing value={m.value??0} size={110} strokeWidth={9} color={m.color}/><div style={{fontSize:11,color:"#555",marginTop:12}}>{m.desc}</div></div>))}</div>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:20}}>HRV · Readiness · RHR</div><ResponsiveContainer width="100%" height={240}><LineChart data={data} margin={{top:5,right:5,bottom:0,left:0}}><CartesianGrid strokeDasharray="3 3" stroke="#1a1d24" vertical={false}/><XAxis dataKey="day" tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false} width={35}/><Tooltip content={<CustomTooltip/>}/><Line type="monotone" dataKey="hrv" name="HRV" stroke="#22d3a5" strokeWidth={2} dot={false} activeDot={{r:4}}/><Line type="monotone" dataKey="readiness" name="Readiness" stroke="#8b5cf6" strokeWidth={2} dot={false} activeDot={{r:4}}/><Line type="monotone" dataKey="rhr" name="RHR" stroke="#e74c3c" strokeWidth={1.5} dot={false} strokeDasharray="4 2" activeDot={{r:4}}/></LineChart></ResponsiveContainer></div>
      </div>)}

      {tab==="sleep"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:24}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:20}}>Last Night</div><div style={{display:"flex",alignItems:"center",gap:24}}><ScoreRing value={Math.round((today.sleep||0)*10)} max={100} size={130} strokeWidth={10} color="#3b82f6" label="Score"/><div style={{flex:1}}><SleepBreakdown data={sleepStages}/></div></div></div>
          <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:24}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:20}}>Sleep Metrics</div><div style={{display:"flex",flexDirection:"column",gap:14}}>{[{label:"Total sleep",value:`${today.sleep??"-"}h`,color:"#3b82f6"},{label:"Bedtime",value:todayRaw.bedtime?new Date(todayRaw.bedtime).toLocaleTimeString("en",{hour:"2-digit",minute:"2-digit"}):"—",color:"#8b5cf6"},{label:"Wake time",value:todayRaw.wakeup?new Date(todayRaw.wakeup).toLocaleTimeString("en",{hour:"2-digit",minute:"2-digit"}):"—",color:"#22d3a5"},{label:"Sleep efficiency",value:todayRaw.sleepEfficiency?`${todayRaw.sleepEfficiency}%`:"—",color:"#f59e0b"},{label:"HRV avg",value:`${today.hrv??"-"} ms`,color:"#22d3a5"}].map(m=>(<div key={m.label} style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontSize:12,color:"#666"}}>{m.label}</span><span style={{fontSize:13,fontWeight:700,color:m.color,fontFamily:"monospace"}}>{m.value}</span></div>))}</div></div>
        </div>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:20}}>Sleep Duration Trend</div><ResponsiveContainer width="100%" height={220}><AreaChart data={data} margin={{top:5,right:5,bottom:0,left:0}}><defs><linearGradient id="sg" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#3b82f6" stopOpacity={0.35}/><stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" stroke="#1a1d24" vertical={false}/><XAxis dataKey="day" tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false}/><YAxis domain={[4,10]} tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false} width={35}/><Tooltip content={<CustomTooltip/>}/><ReferenceLine y={8} stroke="#22d3a5" strokeDasharray="4 2" strokeOpacity={0.4}/><Area type="monotone" dataKey="sleep" name="Sleep" stroke="#3b82f6" fill="url(#sg)" strokeWidth={2} dot={false} activeDot={{r:4}}/></AreaChart></ResponsiveContainer></div>
      </div>)}

      {tab==="activity"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
        <div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12}}>{[{label:"Steps Today",value:today.steps?.toLocaleString(),color:"#f59e0b"},{label:"Calories",value:today.calories,color:"#e74c3c",unit:"kcal"},{label:"Active Min",value:today.activeMinutes,color:"#22d3a5",unit:"min"},{label:"Distance",value:todayRaw.distance?`${(todayRaw.distance/1000).toFixed(1)}`:"-",color:"#3b82f6",unit:"km"}].map(m=>(<div key={m.label} style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:12,padding:18}}><div style={{fontSize:10,color:"#555",textTransform:"uppercase",letterSpacing:"0.08em",marginBottom:8}}>{m.label}</div><div style={{fontSize:26,fontWeight:700,fontFamily:"monospace",color:m.color}}>{m.value??"-"}</div>{m.unit&&<div style={{fontSize:11,color:"#444"}}>{m.unit}</div>}</div>))}</div>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:20}}>Daily Steps</div><ResponsiveContainer width="100%" height={200}><BarChart data={data} margin={{top:5,right:5,bottom:0,left:0}}><CartesianGrid strokeDasharray="3 3" stroke="#1a1d24" vertical={false}/><XAxis dataKey="day" tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false}/><YAxis tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false} width={40}/><Tooltip content={<CustomTooltip/>}/><Bar dataKey="steps" name="Steps" fill="#f59e0b" radius={[3,3,0,0]} opacity={0.85}/></BarChart></ResponsiveContainer></div>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:4}}>Workout Log</div><div style={{fontSize:11,color:"#555",marginBottom:8}}>{realData?"From your Zepp & Ultrahuman exports":"Demo data"}</div>{allWorkouts.slice(0,6).map((w,i)=><WorkoutCard key={i} w={w}/>)}</div>
      </div>)}

      {tab==="trends"&&(<div style={{display:"flex",flexDirection:"column",gap:20}}>
        <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:20}}>Long-term Overview</div><ResponsiveContainer width="100%" height={260}><LineChart data={ALL_ACTIVE.slice(-60).map(d=>({...d,day:d.dayName||d.date}))} margin={{top:5,right:5,bottom:0,left:0}}><CartesianGrid strokeDasharray="3 3" stroke="#1a1d24" vertical={false}/><XAxis dataKey="day" tick={{fill:"#555",fontSize:9}} axisLine={false} tickLine={false} interval={9}/><YAxis tick={{fill:"#555",fontSize:10}} axisLine={false} tickLine={false} width={35}/><Tooltip content={<CustomTooltip/>}/><Line type="monotone" dataKey="hrv" name="HRV" stroke="#22d3a5" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="readiness" name="Readiness" stroke="#8b5cf6" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="sleep" name="Sleep(h)" stroke="#3b82f6" strokeWidth={1.5} dot={false} strokeDasharray="5 2"/></LineChart></ResponsiveContainer></div>
        <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
          <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:16}}>7-day Averages</div>{(()=>{const w=ALL_ACTIVE.slice(-7);const p=ALL_ACTIVE.slice(-14,-7);const avg=(arr,k)=>{const v=arr.map(d=>d[k]).filter(x=>x!=null);return v.length?v.reduce((a,b)=>a+b,0)/v.length:null;};return[{label:"Avg HRV",cur:avg(w,"hrv"),prev:avg(p,"hrv"),unit:"ms",color:"#22d3a5"},{label:"Avg Sleep",cur:avg(w,"sleep")?.toFixed(1),prev:avg(p,"sleep")?.toFixed(1),unit:"h",color:"#3b82f6"},{label:"Avg Steps",cur:Math.round(avg(w,"steps")||0).toLocaleString(),prev:Math.round(avg(p,"steps")||0),unit:"",color:"#f59e0b"},{label:"Avg Readiness",cur:Math.round(avg(w,"readiness")||0),prev:Math.round(avg(p,"readiness")||0),unit:"",color:"#8b5cf6"}].map(m=>(<div key={m.label} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"10px 0",borderBottom:"1px solid #1a1d24"}}><span style={{fontSize:12,color:"#666"}}>{m.label}</span><div style={{textAlign:"right"}}><span style={{fontSize:15,fontWeight:700,color:m.color,fontFamily:"monospace"}}>{m.cur??"-"}{m.unit}</span>{m.prev&&m.cur&&<span style={{fontSize:10,color:parseFloat(m.cur)>=parseFloat(m.prev)?"#22d3a5":"#e74c3c",marginLeft:6}}>{parseFloat(m.cur)>=parseFloat(m.prev)?"▲":"▼"}</span>}</div></div>));})()}</div>
          <div style={{background:"#10121a",border:"1px solid #1e2130",borderRadius:14,padding:20}}><div style={{fontSize:12,fontWeight:700,textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:16}}>Wellness Radar</div><ResponsiveContainer width="100%" height={220}><RadarChart data={(()=>{const w=ALL_ACTIVE.slice(-7);const avg=(k,mx)=>Math.round(Math.min(100,(w.map(d=>d[k]).filter(x=>x!=null).reduce((a,b)=>a+b,0)/(w.filter(d=>d[k]!=null).length||1))/mx*100));return[{metric:"HRV",value:avg("hrv",70)},{metric:"Sleep",value:avg("sleep",8)*8/8},{metric:"Activity",value:avg("steps",10000)},{metric:"Readiness",value:avg("readiness",100)},{metric:"Recovery",value:100-avg("rhr",80)},{metric:"Consistency",value:70}];})()}><PolarGrid stroke="#1e2130"/><PolarAngleAxis dataKey="metric" tick={{fill:"#555",fontSize:10}}/><Radar dataKey="value" stroke="#22d3a5" fill="#22d3a5" fillOpacity={0.15} strokeWidth={1.5}/></RadarChart></ResponsiveContainer></div>
        </div>
      </div>)}
    </div>
  </div>);
}