import JSZip from "jszip";

function parseCSV(text) {
  const lines = text.replace(/^\uFEFF/, "").trim().split("\n");
    if (lines.length < 2) return [];
      const headers = lines[0].split(",").map(h => h.trim().replace(/^"|"$/g, ""));
        return lines.slice(1).map(line => {
            const vals = [];
                let cur = "", inQ = false;
                    for (let i = 0; i < line.length; i++) {
                          if (line[i] === '"') { inQ = !inQ; continue; }
                                if (line[i] === "," && !inQ) { vals.push(cur.trim()); cur = ""; continue; }
                                      cur += line[i];
                                          }
                                              vals.push(cur.trim());
                                                  const obj = {};
                                                      headers.forEach((h, i) => { obj[h] = vals[i] ?? ""; });
                                                          return obj;
                                                            }).filter(r => Object.values(r).some(v => v !== ""));
                                                            }

                                                            export async function parseUltrahuman(zipFile) {
                                                              const zip = await JSZip.loadAsync(zipFile);
                                                                const ringFiles = Object.keys(zip.files).filter(n => n.match(/ring_data_\d+_\d+\.csv$/));
                                                                  const eventFile = Object.keys(zip.files).find(n => n.includes("user_events.csv"));
                                                                    const byDate = {};
                                                                      const ensureDate = (d) => {
                                                                          if (!byDate[d]) byDate[d] = { date: d, hrv_vals: [], hr_vals: [], spo2_vals: [], steps_sum: 0, temp_vals: [], rr_vals: [], workouts: [] };
                                                                            };
                                                                              for (const fname of ringFiles) {
                                                                                  const text = await zip.files[fname].async("string");
                                                                                      const rows = parseCSV(text);
                                                                                          for (const row of rows) {
                                                                                                if (!row.timestamp_epoch || !row.data_type) continue;
                                                                                                      try {
                                                                                                              const ts = parseInt(row.timestamp_epoch);
                                                                                                                      const dt = new Date(ts * 1000).toISOString().slice(0, 10);
                                                                                                                              const val = parseFloat(row.value);
                                                                                                                                      if (isNaN(val)) continue;
                                                                                                                                              ensureDate(dt);
                                                                                                                                                      const d = byDate[dt];
                                                                                                                                                              if (row.data_type === "raw_hrv_2" && val > 0) d.hrv_vals.push(val);
                                                                                                                                                                      else if (row.data_type === "raw_hr" && val > 30 && val < 200) d.hr_vals.push(val);
                                                                                                                                                                              else if (row.data_type === "spo2" && val > 90) d.spo2_vals.push(val);
                                                                                                                                                                                      else if (row.data_type === "steps" && val > 0) d.steps_sum += val;
                                                                                                                                                                                              else if (row.data_type === "temp" && val > 20 && val < 45) d.temp_vals.push(val);
                                                                                                                                                                                                      else if (row.data_type === "respiratory_rate" && val > 5 && val < 40) d.rr_vals.push(val);
                                                                                                                                                                                                            } catch(e) {}
                                                                                                                                                                                                                }
                                                                                                                                                                                                                  }
                                                                                                                                                                                                                    if (eventFile) {
                                                                                                                                                                                                                        const text = await zip.files[eventFile].async("string");
                                                                                                                                                                                                                            const rows = parseCSV(text);
                                                                                                                                                                                                                                for (const row of rows) {
                                                                                                                                                                                                                                      if (!row["Event Time"]) continue;
                                                                                                                                                                                                                                            const dt = row["Event Time"].slice(0, 10);
                                                                                                                                                                                                                                                  ensureDate(dt);
                                                                                                                                                                                                                                                        if (row["Event Type"] === "NATIVE_WORKOUT" || row["Event Type"] === "ACTIVITY") {
                                                                                                                                                                                                                                                                byDate[dt].workouts.push({ name: row["Title"] || row["Event Type"], duration: Math.round((parseInt(row["Duration (seconds)"]) || 0) / 60), startTime: row["Event Time"] });
                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                              const avg = arr => arr.length ? arr.reduce((a, b) => a + b, 0) / arr.length : null;
                                                                                                                                                                                                                                                                                const min = arr => arr.length ? Math.min(...arr) : null;
                                                                                                                                                                                                                                                                                  return Object.entries(byDate).sort(([a],[b]) => a.localeCompare(b)).map(([date, d]) => {
                                                                                                                                                                                                                                                                                      const hrv = d.hrv_vals.length ? Math.round(avg(d.hrv_vals) / 10) : null;
                                                                                                                                                                                                                                                                                          const sorted = [...d.hr_vals].sort((a,b)=>a-b);
                                                                                                                                                                                                                                                                                              const rhr = sorted.length ? Math.round(avg(sorted.slice(0, Math.max(1, Math.floor(sorted.length * 0.1))))) : null;
                                                                                                                                                                                                                                                                                                  const spo2 = d.spo2_vals.length ? +avg(d.spo2_vals).toFixed(1) : null;
                                                                                                                                                                                                                                                                                                      const steps = d.steps_sum > 0 ? Math.round(d.steps_sum) : null;
                                                                                                                                                                                                                                                                                                          const temp = d.temp_vals.length ? +avg(d.temp_vals).toFixed(2) : null;
                                                                                                                                                                                                                                                                                                              const rr = d.rr_vals.length ? +avg(d.rr_vals).toFixed(1) : null;
                                                                                                                                                                                                                                                                                                                  return { date, source: "ultrahuman", hrv, rhr, spo2, steps, temp, rr, workouts: d.workouts };
                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                    export async function parseZepp(zipFile) {
                                                                                                                                                                                                                                                                                                                      const zip = await JSZip.loadAsync(zipFile);
                                                                                                                                                                                                                                                                                                                        const findFile = (pattern) => Object.keys(zip.files).find(n => n.match(pattern));
                                                                                                                                                                                                                                                                                                                          const readCSV = async (fname) => { if (!fname) return []; const text = await zip.files[fname].async("string"); return parseCSV(text); };
                                                                                                                                                                                                                                                                                                                            const sleepFile = findFile(/SLEEP_\d+\.csv$/);
                                                                                                                                                                                                                                                                                                                              const activityFile = findFile(/ACTIVITY_\d+\.csv$/);
                                                                                                                                                                                                                                                                                                                                const sportFile = findFile(/SPORT_\d+\.csv$/);
                                                                                                                                                                                                                                                                                                                                  const hrFile = findFile(/HEARTRATE_AUTO_\d+\.csv$/);
                                                                                                                                                                                                                                                                                                                                    const [sleepRows, activityRows, sportRows, hrRows] = await Promise.all([readCSV(sleepFile), readCSV(activityFile), readCSV(sportFile), readCSV(hrFile)]);
                                                                                                                                                                                                                                                                                                                                      const byDate = {};
                                                                                                                                                                                                                                                                                                                                        const ensureDate = (d) => { if (!byDate[d]) byDate[d] = { date: d }; };
                                                                                                                                                                                                                                                                                                                                          for (const row of sleepRows) {
                                                                                                                                                                                                                                                                                                                                              const date = (row["date"] || row["\uFEFFdate"] || "").trim();
                                                                                                                                                                                                                                                                                                                                                  if (!date) continue;
                                                                                                                                                                                                                                                                                                                                                      ensureDate(date);
                                                                                                                                                                                                                                                                                                                                                          const deep = parseInt(row.deepSleepTime) || 0;
                                                                                                                                                                                                                                                                                                                                                              const light = parseInt(row.shallowSleepTime) || 0;
                                                                                                                                                                                                                                                                                                                                                                  const rem = parseInt(row.REMTime) || 0;
                                                                                                                                                                                                                                                                                                                                                                      const wake = parseInt(row.wakeTime) || 0;
                                                                                                                                                                                                                                                                                                                                                                          const total = deep + light + rem;
                                                                                                                                                                                                                                                                                                                                                                              byDate[date].sleep = total > 0 ? +(total / 60).toFixed(2) : null;
                                                                                                                                                                                                                                                                                                                                                                                  byDate[date].deepSleep = deep > 0 ? +(deep / 60).toFixed(2) : null;
                                                                                                                                                                                                                                                                                                                                                                                      byDate[date].remSleep = rem > 0 ? +(rem / 60).toFixed(2) : null;
                                                                                                                                                                                                                                                                                                                                                                                          byDate[date].lightSleep = light > 0 ? +(light / 60).toFixed(2) : null;
                                                                                                                                                                                                                                                                                                                                                                                              byDate[date].wakeTime = wake;
                                                                                                                                                                                                                                                                                                                                                                                                  byDate[date].bedtime = row.start || null;
                                                                                                                                                                                                                                                                                                                                                                                                      byDate[date].wakeup = row.stop || null;
                                                                                                                                                                                                                                                                                                                                                                                                          byDate[date].sleepEfficiency = (total + wake) > 0 ? Math.round((total / (total + wake)) * 100) : null;
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                              for (const row of activityRows) {
                                                                                                                                                                                                                                                                                                                                                                                                                  const date = (row["date"] || row["\uFEFFdate"] || "").trim();
                                                                                                                                                                                                                                                                                                                                                                                                                      if (!date) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                          ensureDate(date);
                                                                                                                                                                                                                                                                                                                                                                                                                              byDate[date].steps = parseInt(row.steps) || null;
                                                                                                                                                                                                                                                                                                                                                                                                                                  byDate[date].calories = parseInt(row.calories) || null;
                                                                                                                                                                                                                                                                                                                                                                                                                                      byDate[date].distance = parseInt(row.distance) || null;
                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                          const sportTypeMap = { 1:"Outdoor Running", 9:"Indoor Running", 6:"Outdoor Cycling", 52:"Strength Training", 53:"Yoga", 5:"Walking", 4:"Hiking", 78:"HIIT", 8:"Swimming" };
                                                                                                                                                                                                                                                                                                                                                                                                                                            for (const row of sportRows) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                const startTime = row.startTime || "";
                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!startTime) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                        const date = startTime.slice(0, 10);
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ensureDate(date);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!byDate[date].workouts) byDate[date].workouts = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const typeNum = parseInt(row["\uFEFFtype"] || row.type);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        byDate[date].workouts.push({ name: sportTypeMap[typeNum] || `Activity #${typeNum}`, duration: Math.round((parseInt(row["sportTime(s)"]) || 0) / 60), calories: Math.round(parseFloat(row["calories(kcal)"]) || 0), distance: parseFloat(row["distance(m)"]) > 0 ? +(parseFloat(row["distance(m)"]) / 1000).toFixed(2) : null, startTime });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const hrByDate = {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for (const row of hrRows) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const date = (row["date"] || row["\uFEFFdate"] || "").trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const hr = parseInt(row.heartRate);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!date || !hr || hr < 30 || hr > 200) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!hrByDate[date]) hrByDate[date] = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  hrByDate[date].push(hr);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (const [date, hrs] of Object.entries(hrByDate)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ensureDate(date);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const sorted = hrs.sort((a,b) => a-b);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const p10 = sorted.slice(0, Math.max(1, Math.floor(sorted.length * 0.1)));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      byDate[date].rhr = Math.round(p10.reduce((a,b) => a+b, 0) / p10.length);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          byDate[date].avgHR = Math.round(hrs.reduce((a,b) => a+b, 0) / hrs.length);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return Object.entries(byDate).sort(([a],[b]) => a.localeCompare(b)).map(([date, d]) => ({ ...d, source: "zepp" }));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export function mergeData(ultrahumanDays, zeppDays) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const merged = {};
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  for (const d of ultrahumanDays) merged[d.date] = { ...d };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (const d of zeppDays) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (merged[d.date]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              merged[d.date] = { ...merged[d.date], sleep: d.sleep ?? merged[d.date].sleep, deepSleep: d.deepSleep ?? merged[d.date].deepSleep, remSleep: d.remSleep ?? merged[d.date].remSleep, lightSleep: d.lightSleep ?? merged[d.date].lightSleep, wakeTime: d.wakeTime ?? merged[d.date].wakeTime, sleepEfficiency: d.sleepEfficiency ?? merged[d.date].sleepEfficiency, bedtime: d.bedtime ?? merged[d.date].bedtime, wakeup: d.wakeup ?? merged[d.date].wakeup, steps: d.steps ?? merged[d.date].steps, calories: d.calories ?? merged[d.date].calories, distance: d.distance ?? merged[d.date].distance, rhr: merged[d.date].rhr ?? d.rhr, avgHR: d.avgHR ?? merged[d.date].avgHR, workouts: [...(merged[d.date].workouts || []), ...(d.workouts || [])], source: "both" };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        merged[d.date] = { ...d };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Object.values(merged).sort((a,b) => a.date.localeCompare(b.date)).map(d => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const signals = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (d.hrv)   signals.push(Math.min(100, (d.hrv / 60) * 100));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (d.sleep) signals.push(Math.min(100, (d.sleep / 8) * 100));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (d.rhr)   signals.push(Math.max(0, 100 - (d.rhr - 40) * 2));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (d.spo2)  signals.push(Math.min(100, (d.spo2 - 94) * 20));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const readiness = signals.length ? Math.round(signals.reduce((a,b) => a+b,0) / signals.length) : null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const dt = new Date(d.date + "T12:00:00Z");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const displayDate = dt.toLocaleDateString("en", { month: "short", day: "numeric" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const dayName = dt.toLocaleDateString("en", { weekday: "short" });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return { ...d, readiness, displayDate, dayName };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          export async function parseHealthZip(file) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            const zip = await JSZip.loadAsync(file);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const files = Object.keys(zip.files);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                const isUltrahuman = files.some(f => f.match(/ring_data_\d+_\d+\.csv/));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  const isZepp = files.some(f => f.match(/SLEEP_\d+\.csv/));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (isUltrahuman) return { source: "ultrahuman", data: await parseUltrahuman(file) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (isZepp) return { source: "zepp", data: await parseZepp(file) };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        throw new Error("Unrecognized format. Please upload a Ultrahuman or Zepp ZIP.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }